language: php
dist: bionic

notifications:
  email:
    recipients:
        - rdebleu@eWallah.net

sudo: required

services:
  - mysql

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2

env:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master
  - DB=mariadb MOODLE_BRANCH=master

matrix:
  include:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &

install:
  - moodle-plugin-ci install

script:
  - /home/travis/build/moodle/vendor/bin/phpunit "provider_testcase" /home/travis/build/moodle/privacy/tests/provider_test.php
  - /home/travis/build/moodle/vendor/bin/phpunit "tool_dataprivacy_expired_contexts_testcase" /home/travis/build/moodle/admin/tool/dataprivacy/tests/expired_contexts_test.php
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
